<a href="https://colab.research.google.com/github/freddy-7/TI2001B-2023/blob/main/1_Extracci%C3%B3n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
#GOOGLE COLAB
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

ModuleNotFoundError: No module named 'google'

In [3]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

CARGA DE ARCHIVO XLSX

In [4]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx')
df

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [5]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No. CLIENTE        164 non-null    object
 1   NOMBRE             164 non-null    str
 2   FACTURA            164 non-null    str
 3   FECHA_FACTURA      164 non-null    datetime64[us]
 4   FECHA_VENCIMIENTO  164 non-null    datetime64[us]
 5   MONTO ADEUDADO     164 non-null    float64
dtypes: datetime64[us](2), float64(1), object(1), str(2)
memory usage: 7.8+ KB

ITERACIÓN

**Iterar columnas directamente del dataframe**

In [11]:
# Iterar sobre la columna 'nombre'
for nombre in df['NOMBRE']:
    print(nombre)

DONGA HWASUNG MEXICO
DONGA HWASUNG MEXICO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
INDUSTRIAS LANCERMEX
HELVEX
AUTOLIV STEERING WHEELS MEXICO
AUTOLIV STEERING WHEELS MEXICO
BUSSMANN
CLAVOS NACIONALES C.N
CLAVOS NACIONALES C.N
RICHALUM
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
INDUSTRIAS LANCERMEX
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
AUTOLIV STEERING WHEELS MEXICO
PQUISEM
SIEGFRIED RHEIN
SIEGFRIED RHEIN
MOLINERA DE MEXICO
Q SEALS DE MEXICO
Q SEALS DE MEXICO
SIEGFRIED RHEIN
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
DEACERO
TE.MEX AUTOMOTIVE
DIECASTING CELAYA
CLAVOS NACIONALES C.N
CEREALES Y PASTAS
PLENCO DE MEXICO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
DEACERO
GLASSER
NESTLE MEXICO
AIRBUS HELICOPTERS MEXICO QUERETARO
AIRBUS HELICOPTERS MEXICO QUERETARO
SIKA MEXICANA
COVEMEX
HOT MELT SISTEMAS Y SERVICIOS SANCHEZ
EDGAR GARCIA HERNANDEZ
BUSSMANN
SIKA MEXICANA
DWK LIFE SCIENCES
SIEGFRIED RHEIN
DONGA HWASUNG MEXICO
BACHOCO
SIEGFRIED RHEIN
PREFORMADOS DE MEXICO
CEREALES Y PASTAS
EMPACADORA CELAYA
FIDEICOMISO F/1596
DWK LIFE SCIENCES
DONGA HWASUNG MEXICO
DEACERO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
BETA PROCESOS
DEACERO
BEDACOM
NIHON PLAST MEXICANA
GLASSER
CEREALES Y PASTAS
FRESCOS DON GU
DEACERO
KERN LIEBERS MEXICO
PQUISEM
EDGAR GARCIA HERNANDEZ
KERN LIEBERS MEXICO
DEACERO
CONTROLADORA MABE
ITW POLY MEX
ANA BARBARA CRUZ PALACIOS
ARMANDO VIDAURRETA PEÑA
CEREALES Y PASTAS
DISTRIBUCIONES Y REPRESENTACIONES CALORA
OERLIKON BALZERS COATING MEXICO
APEX TOOL GROUP MANUFACTURING MEXICO
SIEGFRIED RHEIN
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
HOBBY ELECTRONICA
DAVID LICEA PANDURO
CEREALES Y PASTAS
INDUSTRIAS TOLJY
SANKO GOSEI MEXICO
VINILOS
CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS INDUSTRIALES
EDGAR GARCIA HERNANDEZ
KERN LIEBERS MEXICO
RL ELECTRICO
BETA PROCESOS
ITW POLY MEX
PERFORMANCE COATING
ADVANEX DE MEXICO
J. FRANCISCO FERRUZCA HERNANDEZ
DEACERO
MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACCION DEL CENTRO
PRODUCTOS PENNSYLVANIA
SIEGFRIED RHEIN
MEXICANA DE INGENIERIA Y MAQUINARIA
APEX TOOL GROUP MANUFACTURING MEXICO
PRODUCTOS PENNSYLVANIA
PÚBLICO EN GENERAL
RAUL SERVIN AGUILLON
BLANCA ROCIO GARCIA MORALES
VINILOS
ALIMENTOS GOURMET DEL BAJIO
DEACERO
JORGE HERBERT PEREZ
CAPTIVE SPORT
CEREALES Y PASTAS
ELASTOMEROS DE QUERETARO
ABASTECEDORA GOURMET
LBQ FOUNDRY
FRESCOPACK
MARI CARMEN ALONZO MORA
HOSPITAL SAN JOSE DE CELAYA
SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUSTRIAL
CARLOS ALBERTO HERNANDEZ MIRANDA
DEX STAR
VINILOS
EMZ HANAUER DE MEXICO
OSANIA CLEANING & SANITIZING
KERN LIEBERS MEXICO
MECAPRIM SERVICIOS INDUSTRIALES
JAKBA-SEE
MULTI EQUIPOS AUTOMOTRICES VIZU
GRUPO ROCE INDUSTRIAL Y COMERCIAL
JOSE ALEJANDRO DIAZ NIETO
GRUPO ROCE INDUSTRIAL Y COMERCIAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
TERMOFORMADOS
MARATHON SYSTEMS CONTROL
FRANCISCO JAVIER MEDINA SANCHEZ
GABRIELA GARCIA SANCHEZ
MECAPRIM SERVICIOS INDUSTRIALES
JOSE ALEJANDRO DIAZ NIETO
JV AGRO
UCH COMERCIAL
POLIETILENOS Y PRODUCTOS DE QUERETARO
PÚBLICO EN GENERAL
DISTRIBUIDORA LIVERPOOL
TRATAMIENTOS TERMICOS DE QUERETARO
PÚBLICO EN GENERAL
CAPTIVE SPORT
HEVACSA TERMOENCOGIBLES
ELECTRO FERRETERA REAL
SCIMPLA
ANA KARLA ROSALES VAZQUEZ
LBQ FOUNDRY
MANUFACTURERA SLY
PÚBLICO EN GENERAL
J H MILLS
PÚBLICO EN GENERAL
BURBUPAC DE QUERETARO
AT Y V DESARROLLOS Y MANUFACTURAS
PÚBLICO EN GENERAL
OLMO RACKS & DUNNAGE
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
FISHERS QUERETARO

***USANDO NUMPY***

**Iterar columnas tipo STRING**

In [6]:
# Iterar sobre una columna tipo string: 'NOMBRE' con Numpy
nombres = df['NOMBRE'].to_numpy() #Primero convertimos la columna en un array

# Iterar sobre el array
for nombre in np.nditer(nombres, flags=['refs_ok']): #Usamos flags=['refs_ok'] si la columna contiene strings (objetos) en lugar de números
    print(nombre.item())  # item() lo convierte a string nativo de Python

DONGA HWASUNG MEXICO
DONGA HWASUNG MEXICO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
INDUSTRIAS LANCERMEX
HELVEX
AUTOLIV STEERING WHEELS MEXICO
AUTOLIV STEERING WHEELS MEXICO
BUSSMANN
CLAVOS NACIONALES C.N
CLAVOS NACIONALES C.N
RICHALUM
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
INDUSTRIAS LANCERMEX
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
AUTOLIV STEERING WHEELS MEXICO
PQUISEM
SIEGFRIED RHEIN
SIEGFRIED RHEIN
MOLINERA DE MEXICO
Q SEALS DE MEXICO
Q SEALS DE MEXICO
SIEGFRIED RHEIN
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
DEACERO
TE.MEX AUTOMOTIVE
DIECASTING CELAYA
CLAVOS NACIONALES C.N
CEREALES Y PASTAS
PLENCO DE MEXICO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
DEACERO
GLASSER
NESTLE MEXICO
AIRBUS HELICOPTERS MEXICO QUERETARO
AIRBUS HELICOPTERS MEXICO QUERETARO
SIKA MEXICANA
COVEMEX
HOT MELT SISTEMAS Y SERVICIOS SANCHEZ
EDGAR GARCIA HERNANDEZ
BUSSMANN
SIKA MEXICANA
DWK LIFE SCIENCES
SIEGFRIED RHEIN
DONGA HWASUNG MEXICO
BACHOCO
SIEGFRIED RHEIN
PREFORMADOS DE MEXICO
CEREALES Y PASTAS
EMPACADORA CELAYA
FIDEICOMISO F/1596
DWK LIFE SCIENCES
DONGA HWASUNG MEXICO
DEACERO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
BETA PROCESOS
DEACERO
BEDACOM
NIHON PLAST MEXICANA
GLASSER
CEREALES Y PASTAS
FRESCOS DON GU
DEACERO
KERN LIEBERS MEXICO
PQUISEM
EDGAR GARCIA HERNANDEZ
KERN LIEBERS MEXICO
DEACERO
CONTROLADORA MABE
ITW POLY MEX
ANA BARBARA CRUZ PALACIOS
ARMANDO VIDAURRETA PEÑA
CEREALES Y PASTAS
DISTRIBUCIONES Y REPRESENTACIONES CALORA
OERLIKON BALZERS COATING MEXICO
APEX TOOL GROUP MANUFACTURING MEXICO
SIEGFRIED RHEIN
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
HOBBY ELECTRONICA
DAVID LICEA PANDURO
CEREALES Y PASTAS
INDUSTRIAS TOLJY
SANKO GOSEI MEXICO
VINILOS
CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS INDUSTRIALES
EDGAR GARCIA HERNANDEZ
KERN LIEBERS MEXICO
RL ELECTRICO
BETA PROCESOS
ITW POLY MEX
PERFORMANCE COATING
ADVANEX DE MEXICO
J. FRANCISCO FERRUZCA HERNANDEZ
DEACERO
MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACCION DEL CENTRO
PRODUCTOS PENNSYLVANIA
SIEGFRIED RHEIN
MEXICANA DE INGENIERIA Y MAQUINARIA
APEX TOOL GROUP MANUFACTURING MEXICO
PRODUCTOS PENNSYLVANIA
PÚBLICO EN GENERAL
RAUL SERVIN AGUILLON
BLANCA ROCIO GARCIA MORALES
VINILOS
ALIMENTOS GOURMET DEL BAJIO
DEACERO
JORGE HERBERT PEREZ
CAPTIVE SPORT
CEREALES Y PASTAS
ELASTOMEROS DE QUERETARO
ABASTECEDORA GOURMET
LBQ FOUNDRY
FRESCOPACK
MARI CARMEN ALONZO MORA
HOSPITAL SAN JOSE DE CELAYA
SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUSTRIAL
CARLOS ALBERTO HERNANDEZ MIRANDA
DEX STAR
VINILOS
EMZ HANAUER DE MEXICO
OSANIA CLEANING & SANITIZING
KERN LIEBERS MEXICO
MECAPRIM SERVICIOS INDUSTRIALES
JAKBA-SEE
MULTI EQUIPOS AUTOMOTRICES VIZU
GRUPO ROCE INDUSTRIAL Y COMERCIAL
JOSE ALEJANDRO DIAZ NIETO
GRUPO ROCE INDUSTRIAL Y COMERCIAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
TERMOFORMADOS
MARATHON SYSTEMS CONTROL
FRANCISCO JAVIER MEDINA SANCHEZ
GABRIELA GARCIA SANCHEZ
MECAPRIM SERVICIOS INDUSTRIALES
JOSE ALEJANDRO DIAZ NIETO
JV AGRO
UCH COMERCIAL
POLIETILENOS Y PRODUCTOS DE QUERETARO
PÚBLICO EN GENERAL
DISTRIBUIDORA LIVERPOOL
TRATAMIENTOS TERMICOS DE QUERETARO
PÚBLICO EN GENERAL
CAPTIVE SPORT
HEVACSA TERMOENCOGIBLES
ELECTRO FERRETERA REAL
SCIMPLA
ANA KARLA ROSALES VAZQUEZ
LBQ FOUNDRY
MANUFACTURERA SLY
PÚBLICO EN GENERAL
J H MILLS
PÚBLICO EN GENERAL
BURBUPAC DE QUERETARO
AT Y V DESARROLLOS Y MANUFACTURAS
PÚBLICO EN GENERAL
OLMO RACKS & DUNNAGE
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
FISHERS QUERETARO

**Iterar columnas tipo NUMÉRICO**

In [7]:
# Iterar sobre una columna tipo numérico: 'MONTO ADEUDADO' con Numpy
monto_adeudado = df['MONTO ADEUDADO'].to_numpy() # Convertir la columna 'MONTO ADEUDADO' a array de NumPy

# Iterar sobre el array
for monto_adeudado in np.nditer(monto_adeudado):
    print(monto_adeudado)  # monto_adeudado es directamente un número (int o float)

97485.94
97485.94
64916.21
52715.74
50639.8
49416.0
49416.0
48882.12
45216.34
45216.34
42880.05
37588.59
35143.82
34493.76
32886.0
30880.31
30276.0
30276.0
29642.92
29562.6
29197.72
26795.86
25670.22
23872.8
22956.4
21440.02
21179.28
20610.88
19301.82
17975.65
17579.52
17400.0
17271.23
16240.0
16240.0
15878.08
15843.28
13747.65
13086.19
12474.0
12057.04
11067.54
11019.94
10759.0
10565.28
10467.83
10440.0
10226.56
10092.0
9540.77
9472.53
9396.0
9032.92
8653.6
8653.6
8463.31
8266.67
8243.54
8190.46
7882.4
7714.0
7081.8
6840.66
6820.8
6612.0
6496.0
6438.19
6351.0
6264.0
6264.0
5967.85
5827.84
5800.0
5660.8
5502.81
5474.5
5443.47
5414.3
5373.1
5313.73
5253.51
4721.2
4640.0
4541.4
4512.28
4292.0
4173.62
4158.6
4080.3
4022.13
3971.93
3830.0
3480.0
3451.0
3399.38
3375.14
3368.64
3248.58
3183.04
3166.38
2756.16
2694.95
2526.48
2334.5
2256.14
2094.96
2088.0
2000.0
1949.38
1925.6
1827.0
1740.79
1740.0
1682.0
1682.0
1647.2
1608.15
1479.0
1401.57
1390.72
1264.4
1229.95
1204.08
1179.95
1169.28
1095.85
1068.28
1015.0
1000.0
1000.0
1000.0
815.0
799.24
765.6
763.04
754.0
742.4
730.01
704.41
702.96
658.6
591.6
568.4
555.19
500.0
500.0
487.2
487.2
420.0
406.0
366.04
313.5
300.0
262.74
200.0
191.04
139.2
130.0
87.35
56.0
45.0
40.0
24.01
19.94

**Iterar Filas**

In [25]:
# Iterar sobre cada fila del dataframe
for index, row in df.iterrows():
    print(f"Fila {index}:")
    print(f"NOMBRE: {row['NOMBRE']}")
    print(f"FECHA DE VENCIMIENTO: {row['FECHA_VENCIMIENTO']}")
    print("-----")

Fila 0:
NOMBRE: DONGA HWASUNG MEXICO
FECHA DE VENCIMIENTO: 2023-03-26 00:00:00
-----
Fila 1:
NOMBRE: DONGA HWASUNG MEXICO
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 2:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 3:
NOMBRE: INDUSTRIAS LANCERMEX
FECHA DE VENCIMIENTO: 2023-03-25 00:00:00
-----
Fila 4:
NOMBRE: HELVEX
FECHA DE VENCIMIENTO: 2023-04-03 00:00:00
-----
Fila 5:
NOMBRE: AUTOLIV STEERING WHEELS MEXICO
FECHA DE VENCIMIENTO: 2023-03-25 00:00:00
-----
Fila 6:
NOMBRE: AUTOLIV STEERING WHEELS MEXICO
FECHA DE VENCIMIENTO: 2023-05-07 00:00:00
-----
Fila 7:
NOMBRE: BUSSMANN
FECHA DE VENCIMIENTO: 2023-02-04 00:00:00
-----
Fila 8:
NOMBRE: CLAVOS NACIONALES C.N
FECHA DE VENCIMIENTO: 2023-05-12 00:00:00
-----
Fila 9:
NOMBRE: CLAVOS NACIONALES C.N
FECHA DE VENCIMIENTO: 2023-05-13 00:00:00
-----
Fila 10:
NOMBRE: RICHALUM
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 11:
NOMBRE: TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-03-12 00:00:00
-----
Fila 12:
NOMBRE: INDUSTRIAS LANCERMEX
FECHA DE VENCIMIENTO: 2023-03-11 00:00:00
-----
Fila 13:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-03-19 00:00:00
-----
Fila 14:
NOMBRE: AUTOLIV STEERING WHEELS MEXICO
FECHA DE VENCIMIENTO: 2023-03-06 00:00:00
-----
Fila 15:
NOMBRE: PQUISEM
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 16:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-02-27 00:00:00
-----
Fila 17:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-03-04 00:00:00
-----
Fila 18:
NOMBRE: MOLINERA DE MEXICO
FECHA DE VENCIMIENTO: 2023-03-29 00:00:00
-----
Fila 19:
NOMBRE: Q SEALS DE MEXICO
FECHA DE VENCIMIENTO: 2023-05-12 00:00:00
-----
Fila 20:
NOMBRE: Q SEALS DE MEXICO
FECHA DE VENCIMIENTO: 2023-04-02 00:00:00
-----
Fila 21:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-04-10 00:00:00
-----
Fila 22:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 23:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2023-04-16 00:00:00
-----
Fila 24:
NOMBRE: TE.MEX AUTOMOTIVE
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 25:
NOMBRE: DIECASTING CELAYA
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 26:
NOMBRE: CLAVOS NACIONALES C.N
FECHA DE VENCIMIENTO: 2023-03-26 00:00:00
-----
Fila 27:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 28:
NOMBRE: PLENCO DE MEXICO
FECHA DE VENCIMIENTO: 2023-03-18 00:00:00
-----
Fila 29:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 30:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2023-01-22 00:00:00
-----
Fila 31:
NOMBRE: GLASSER
FECHA DE VENCIMIENTO: 2023-02-03 00:00:00
-----
Fila 32:
NOMBRE: NESTLE MEXICO
FECHA DE VENCIMIENTO: 2023-03-01 00:00:00
-----
Fila 33:
NOMBRE: AIRBUS HELICOPTERS MEXICO QUERETARO
FECHA DE VENCIMIENTO: 2023-04-04 00:00:00
-----
Fila 34:
NOMBRE: AIRBUS HELICOPTERS MEXICO QUERETARO
FECHA DE VENCIMIENTO: 2023-04-04 00:00:00
-----
Fila 35:
NOMBRE: SIKA MEXICANA
FECHA DE VENCIMIENTO: 2023-04-07 00:00:00
-----
Fila 36:
NOMBRE: COVEMEX
FECHA DE VENCIMIENTO: 2023-03-29 00:00:00
-----
Fila 37:
NOMBRE: HOT MELT SISTEMAS Y SERVICIOS SANCHEZ
FECHA DE VENCIMIENTO: 2023-03-03 00:00:00
-----
Fila 38:
NOMBRE: EDGAR GARCIA HERNANDEZ
FECHA DE VENCIMIENTO: 2023-03-28 00:00:00
-----
Fila 39:
NOMBRE: BUSSMANN
FECHA DE VENCIMIENTO: 2022-11-15 00:00:00
-----
Fila 40:
NOMBRE: SIKA MEXICANA
FECHA DE VENCIMIENTO: 2023-04-06 00:00:00
-----
Fila 41:
NOMBRE: DWK LIFE SCIENCES
FECHA DE VENCIMIENTO: 2023-03-01 00:00:00
-----
Fila 42:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-03-25 00:00:00
-----
Fila 43:
NOMBRE: DONGA HWASUNG MEXICO
FECHA DE VENCIMIENTO: 2023-04-07 00:00:00
-----
Fila 44:
NOMBRE: BACHOCO
FECHA DE VENCIMIENTO: 2022-01-22 00:00:00
-----
Fila 45:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-04-10 00:00:00
-----
Fila 46:
NOMBRE: PREFORMADOS DE MEXICO
FECHA DE VENCIMIENTO: 2023-03-31 00:00:00
-----
Fila 47:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 48:
NOMBRE: EMPACADORA CELAYA
FECHA DE VENCIMIENTO: 2022-08-13 00:00:00
-----
Fila 49:
NOMBRE: FIDEICOMISO F/1596
FECHA DE VENCIMIENTO: 2023-03-09 00:00:00
-----
Fila 50:
NOMBRE: DWK LIFE SCIENCES
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 51:
NOMBRE: DONGA HWASUNG MEXICO
FECHA DE VENCIMIENTO: 2023-03-29 00:00:00
-----
Fila 52:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2022-10-09 00:00:00
-----
Fila 53:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-01-21 00:00:00
-----
Fila 54:
NOMBRE: PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
FECHA DE VENCIMIENTO: 2023-03-04 00:00:00
-----
Fila 55:
NOMBRE: TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-04-07 00:00:00
-----
Fila 56:
NOMBRE: BETA PROCESOS
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 57:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2022-11-05 00:00:00
-----
Fila 58:
NOMBRE: BEDACOM
FECHA DE VENCIMIENTO: 2021-12-09 00:00:00
-----
Fila 59:
NOMBRE: NIHON PLAST MEXICANA
FECHA DE VENCIMIENTO: 2023-03-17 00:00:00
-----
Fila 60:
NOMBRE: GLASSER
FECHA DE VENCIMIENTO: 2023-02-03 00:00:00
-----
Fila 61:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 62:
NOMBRE: FRESCOS DON GU
FECHA DE VENCIMIENTO: 2023-03-23 00:00:00
-----
Fila 63:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2023-04-16 00:00:00
-----
Fila 64:
NOMBRE: KERN LIEBERS MEXICO
FECHA DE VENCIMIENTO: 2023-02-14 00:00:00
-----
Fila 65:
NOMBRE: PQUISEM
FECHA DE VENCIMIENTO: 2023-03-21 00:00:00
-----
Fila 66:
NOMBRE: EDGAR GARCIA HERNANDEZ
FECHA DE VENCIMIENTO: 2023-03-11 00:00:00
-----
Fila 67:
NOMBRE: KERN LIEBERS MEXICO
FECHA DE VENCIMIENTO: 2023-03-26 00:00:00
-----
Fila 68:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2023-04-29 00:00:00
-----
Fila 69:
NOMBRE: CONTROLADORA MABE
FECHA DE VENCIMIENTO: 2022-10-26 00:00:00
-----
Fila 70:
NOMBRE: ITW POLY MEX
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 71:
NOMBRE: ANA BARBARA CRUZ PALACIOS
FECHA DE VENCIMIENTO: 2023-03-31 00:00:00
-----
Fila 72:
NOMBRE: ARMANDO VIDAURRETA PEÑA
FECHA DE VENCIMIENTO: 2022-12-14 00:00:00
-----
Fila 73:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 74:
NOMBRE: DISTRIBUCIONES Y REPRESENTACIONES CALORA
FECHA DE VENCIMIENTO: 2023-04-22 00:00:00
-----
Fila 75:
NOMBRE: OERLIKON BALZERS COATING MEXICO
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 76:
NOMBRE: APEX TOOL GROUP MANUFACTURING MEXICO
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 77:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-04-17 00:00:00
-----
Fila 78:
NOMBRE: TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-03-18 00:00:00
-----
Fila 79:
NOMBRE: HOBBY ELECTRONICA
FECHA DE VENCIMIENTO: 2023-04-05 00:00:00
-----
Fila 80:
NOMBRE: DAVID LICEA PANDURO
FECHA DE VENCIMIENTO: 2023-03-09 00:00:00
-----
Fila 81:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 82:
NOMBRE: INDUSTRIAS TOLJY
FECHA DE VENCIMIENTO: 2023-03-03 00:00:00
-----
Fila 83:
NOMBRE: SANKO GOSEI MEXICO
FECHA DE VENCIMIENTO: 2023-02-17 00:00:00
-----
Fila 84:
NOMBRE: VINILOS
FECHA DE VENCIMIENTO: 2023-03-31 00:00:00
-----
Fila 85:
NOMBRE: CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 86:
NOMBRE: EDGAR GARCIA HERNANDEZ
FECHA DE VENCIMIENTO: 2023-02-17 00:00:00
-----
Fila 87:
NOMBRE: KERN LIEBERS MEXICO
FECHA DE VENCIMIENTO: 2023-03-19 00:00:00
-----
Fila 88:
NOMBRE: RL ELECTRICO
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 89:
NOMBRE: BETA PROCESOS
FECHA DE VENCIMIENTO: 2023-03-30 00:00:00
-----
Fila 90:
NOMBRE: ITW POLY MEX
FECHA DE VENCIMIENTO: 2023-04-12 00:00:00
-----
Fila 91:
NOMBRE: PERFORMANCE COATING
FECHA DE VENCIMIENTO: 2021-01-18 00:00:00
-----
Fila 92:
NOMBRE: ADVANEX DE MEXICO
FECHA DE VENCIMIENTO: 2022-05-06 00:00:00
-----
Fila 93:
NOMBRE: J. FRANCISCO FERRUZCA HERNANDEZ
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 94:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2022-12-10 00:00:00
-----
Fila 95:
NOMBRE: MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACCION DEL CENTRO
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 96:
NOMBRE: PRODUCTOS PENNSYLVANIA
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 97:
NOMBRE: SIEGFRIED RHEIN
FECHA DE VENCIMIENTO: 2023-02-20 00:00:00
-----
Fila 98:
NOMBRE: MEXICANA DE INGENIERIA Y MAQUINARIA
FECHA DE VENCIMIENTO: 2023-03-04 00:00:00
-----
Fila 99:
NOMBRE: APEX TOOL GROUP MANUFACTURING MEXICO
FECHA DE VENCIMIENTO: 2023-03-26 00:00:00
-----
Fila 100:
NOMBRE: PRODUCTOS PENNSYLVANIA
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 101:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 102:
NOMBRE: RAUL SERVIN AGUILLON
FECHA DE VENCIMIENTO: 2023-03-15 00:00:00
-----
Fila 103:
NOMBRE: BLANCA ROCIO GARCIA MORALES
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 104:
NOMBRE: VINILOS
FECHA DE VENCIMIENTO: 2023-03-31 00:00:00
-----
Fila 105:
NOMBRE: ALIMENTOS GOURMET DEL BAJIO
FECHA DE VENCIMIENTO: 2021-08-23 00:00:00
-----
Fila 106:
NOMBRE: DEACERO
FECHA DE VENCIMIENTO: 2022-11-05 00:00:00
-----
Fila 107:
NOMBRE: JORGE HERBERT PEREZ
FECHA DE VENCIMIENTO: 2021-08-23 00:00:00
-----
Fila 108:
NOMBRE: CAPTIVE SPORT
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 109:
NOMBRE: CEREALES Y PASTAS
FECHA DE VENCIMIENTO: 2023-03-24 00:00:00
-----
Fila 110:
NOMBRE: ELASTOMEROS DE QUERETARO
FECHA DE VENCIMIENTO: 2023-04-12 00:00:00
-----
Fila 111:
NOMBRE: ABASTECEDORA GOURMET
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 112:
NOMBRE: LBQ FOUNDRY
FECHA DE VENCIMIENTO: 2023-03-09 00:00:00
-----
Fila 113:
NOMBRE: FRESCOPACK
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 114:
NOMBRE: MARI CARMEN ALONZO MORA
FECHA DE VENCIMIENTO: 2023-02-27 00:00:00
-----
Fila 115:
NOMBRE: HOSPITAL SAN JOSE DE CELAYA
FECHA DE VENCIMIENTO: 2021-08-28 00:00:00
-----
Fila 116:
NOMBRE: SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUSTRIAL
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 117:
NOMBRE: CARLOS ALBERTO HERNANDEZ MIRANDA
FECHA DE VENCIMIENTO: 2023-01-16 00:00:00
-----
Fila 118:
NOMBRE: DEX STAR
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 119:
NOMBRE: VINILOS
FECHA DE VENCIMIENTO: 2023-03-31 00:00:00
-----
Fila 120:
NOMBRE: EMZ HANAUER DE MEXICO
FECHA DE VENCIMIENTO: 2023-02-08 00:00:00
-----
Fila 121:
NOMBRE: OSANIA CLEANING & SANITIZING
FECHA DE VENCIMIENTO: 2022-11-05 00:00:00
-----
Fila 122:
NOMBRE: KERN LIEBERS MEXICO
FECHA DE VENCIMIENTO: 2023-02-14 00:00:00
-----
Fila 123:
NOMBRE: MECAPRIM SERVICIOS INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-03-15 00:00:00
-----
Fila 124:
NOMBRE: JAKBA-SEE
FECHA DE VENCIMIENTO: 2023-03-16 00:00:00
-----
Fila 125:
NOMBRE: MULTI EQUIPOS AUTOMOTRICES VIZU
FECHA DE VENCIMIENTO: 2023-01-31 00:00:00
-----
Fila 126:
NOMBRE: GRUPO ROCE INDUSTRIAL Y COMERCIAL
FECHA DE VENCIMIENTO: 2023-01-31 00:00:00
-----
Fila 127:
NOMBRE: JOSE ALEJANDRO DIAZ NIETO
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 128:
NOMBRE: GRUPO ROCE INDUSTRIAL Y COMERCIAL
FECHA DE VENCIMIENTO: 2023-02-02 00:00:00
-----
Fila 129:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-10-05 00:00:00
-----
Fila 130:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2022-01-27 00:00:00
-----
Fila 131:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-08-16 00:00:00
-----
Fila 132:
NOMBRE: TERMOFORMADOS
FECHA DE VENCIMIENTO: 2023-04-13 00:00:00
-----
Fila 133:
NOMBRE: MARATHON SYSTEMS CONTROL
FECHA DE VENCIMIENTO: 2023-02-11 00:00:00
-----
Fila 134:
NOMBRE: FRANCISCO JAVIER MEDINA SANCHEZ
FECHA DE VENCIMIENTO: 2022-10-27 00:00:00
-----
Fila 135:
NOMBRE: GABRIELA GARCIA SANCHEZ
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 136:
NOMBRE: MECAPRIM SERVICIOS INDUSTRIALES
FECHA DE VENCIMIENTO: 2023-03-15 00:00:00
-----
Fila 137:
NOMBRE: JOSE ALEJANDRO DIAZ NIETO
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 138:
NOMBRE: JV AGRO
FECHA DE VENCIMIENTO: 2023-03-15 00:00:00
-----
Fila 139:
NOMBRE: UCH COMERCIAL
FECHA DE VENCIMIENTO: 2023-03-14 00:00:00
-----
Fila 140:
NOMBRE: POLIETILENOS Y PRODUCTOS DE QUERETARO
FECHA DE VENCIMIENTO: 2023-03-16 00:00:00
-----
Fila 141:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-08-06 00:00:00
-----
Fila 142:
NOMBRE: DISTRIBUIDORA LIVERPOOL
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 143:
NOMBRE: TRATAMIENTOS TERMICOS DE QUERETARO
FECHA DE VENCIMIENTO: 2023-02-01 00:00:00
-----
Fila 144:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-11-09 00:00:00
-----
Fila 145:
NOMBRE: CAPTIVE SPORT
FECHA DE VENCIMIENTO: 2021-09-06 00:00:00
-----
Fila 146:
NOMBRE: HEVACSA TERMOENCOGIBLES
FECHA DE VENCIMIENTO: 2023-03-07 00:00:00
-----
Fila 147:
NOMBRE: ELECTRO FERRETERA REAL
FECHA DE VENCIMIENTO: 2023-03-08 00:00:00
-----
Fila 148:
NOMBRE: SCIMPLA
FECHA DE VENCIMIENTO: 2022-05-10 00:00:00
-----
Fila 149:
NOMBRE: ANA KARLA ROSALES VAZQUEZ
FECHA DE VENCIMIENTO: 2023-02-07 00:00:00
-----
Fila 150:
NOMBRE: LBQ FOUNDRY
FECHA DE VENCIMIENTO: 2023-03-18 00:00:00
-----
Fila 151:
NOMBRE: MANUFACTURERA SLY
FECHA DE VENCIMIENTO: 2023-03-10 00:00:00
-----
Fila 152:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-08-26 00:00:00
-----
Fila 153:
NOMBRE: J H MILLS
FECHA DE VENCIMIENTO: 2023-03-07 00:00:00
-----
Fila 154:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2021-08-31 00:00:00
-----
Fila 155:
NOMBRE: BURBUPAC DE QUERETARO
FECHA DE VENCIMIENTO: 2023-04-07 00:00:00
-----
Fila 156:
NOMBRE: AT Y V DESARROLLOS Y MANUFACTURAS
FECHA DE VENCIMIENTO: 2023-03-15 00:00:00
-----
Fila 157:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2023-03-13 00:00:00
-----
Fila 158:
NOMBRE: OLMO RACKS & DUNNAGE
FECHA DE VENCIMIENTO: 2022-06-28 00:00:00
-----
Fila 159:
NOMBRE: CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL
FECHA DE VENCIMIENTO: 2023-01-31 00:00:00
-----
Fila 160:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2023-03-07 00:00:00
-----
Fila 161:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2023-03-09 00:00:00
-----
Fila 162:
NOMBRE: PÚBLICO EN GENERAL
FECHA DE VENCIMIENTO: 2023-03-09 00:00:00
-----
Fila 163:
NOMBRE: FISHERS QUERETARO
FECHA DE VENCIMIENTO: 2022-05-27 00:00:00
-----

**OPERACIONES FUNDAMENTALES**

In [8]:
#Convertir cada nombre a mayúsculas
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.upper())

DONGA HWASUNG MEXICO
DONGA HWASUNG MEXICO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
INDUSTRIAS LANCERMEX
HELVEX
AUTOLIV STEERING WHEELS MEXICO
AUTOLIV STEERING WHEELS MEXICO
BUSSMANN
CLAVOS NACIONALES C.N
CLAVOS NACIONALES C.N
RICHALUM
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
INDUSTRIAS LANCERMEX
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
AUTOLIV STEERING WHEELS MEXICO
PQUISEM
SIEGFRIED RHEIN
SIEGFRIED RHEIN
MOLINERA DE MEXICO
Q SEALS DE MEXICO
Q SEALS DE MEXICO
SIEGFRIED RHEIN
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
DEACERO
TE.MEX AUTOMOTIVE
DIECASTING CELAYA
CLAVOS NACIONALES C.N
CEREALES Y PASTAS
PLENCO DE MEXICO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
DEACERO
GLASSER
NESTLE MEXICO
AIRBUS HELICOPTERS MEXICO QUERETARO
AIRBUS HELICOPTERS MEXICO QUERETARO
SIKA MEXICANA
COVEMEX
HOT MELT SISTEMAS Y SERVICIOS SANCHEZ
EDGAR GARCIA HERNANDEZ
BUSSMANN
SIKA MEXICANA
DWK LIFE SCIENCES
SIEGFRIED RHEIN
DONGA HWASUNG MEXICO
BACHOCO
SIEGFRIED RHEIN
PREFORMADOS DE MEXICO
CEREALES Y PASTAS
EMPACADORA CELAYA
FIDEICOMISO F/1596
DWK LIFE SCIENCES
DONGA HWASUNG MEXICO
DEACERO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
BETA PROCESOS
DEACERO
BEDACOM
NIHON PLAST MEXICANA
GLASSER
CEREALES Y PASTAS
FRESCOS DON GU
DEACERO
KERN LIEBERS MEXICO
PQUISEM
EDGAR GARCIA HERNANDEZ
KERN LIEBERS MEXICO
DEACERO
CONTROLADORA MABE
ITW POLY MEX
ANA BARBARA CRUZ PALACIOS
ARMANDO VIDAURRETA PEÑA
CEREALES Y PASTAS
DISTRIBUCIONES Y REPRESENTACIONES CALORA
OERLIKON BALZERS COATING MEXICO
APEX TOOL GROUP MANUFACTURING MEXICO
SIEGFRIED RHEIN
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES
HOBBY ELECTRONICA
DAVID LICEA PANDURO
CEREALES Y PASTAS
INDUSTRIAS TOLJY
SANKO GOSEI MEXICO
VINILOS
CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS INDUSTRIALES
EDGAR GARCIA HERNANDEZ
KERN LIEBERS MEXICO
RL ELECTRICO
BETA PROCESOS
ITW POLY MEX
PERFORMANCE COATING
ADVANEX DE MEXICO
J. FRANCISCO FERRUZCA HERNANDEZ
DEACERO
MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACCION DEL CENTRO
PRODUCTOS PENNSYLVANIA
SIEGFRIED RHEIN
MEXICANA DE INGENIERIA Y MAQUINARIA
APEX TOOL GROUP MANUFACTURING MEXICO
PRODUCTOS PENNSYLVANIA
PÚBLICO EN GENERAL
RAUL SERVIN AGUILLON
BLANCA ROCIO GARCIA MORALES
VINILOS
ALIMENTOS GOURMET DEL BAJIO
DEACERO
JORGE HERBERT PEREZ
CAPTIVE SPORT
CEREALES Y PASTAS
ELASTOMEROS DE QUERETARO
ABASTECEDORA GOURMET
LBQ FOUNDRY
FRESCOPACK
MARI CARMEN ALONZO MORA
HOSPITAL SAN JOSE DE CELAYA
SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUSTRIAL
CARLOS ALBERTO HERNANDEZ MIRANDA
DEX STAR
VINILOS
EMZ HANAUER DE MEXICO
OSANIA CLEANING & SANITIZING
KERN LIEBERS MEXICO
MECAPRIM SERVICIOS INDUSTRIALES
JAKBA-SEE
MULTI EQUIPOS AUTOMOTRICES VIZU
GRUPO ROCE INDUSTRIAL Y COMERCIAL
JOSE ALEJANDRO DIAZ NIETO
GRUPO ROCE INDUSTRIAL Y COMERCIAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
TERMOFORMADOS
MARATHON SYSTEMS CONTROL
FRANCISCO JAVIER MEDINA SANCHEZ
GABRIELA GARCIA SANCHEZ
MECAPRIM SERVICIOS INDUSTRIALES
JOSE ALEJANDRO DIAZ NIETO
JV AGRO
UCH COMERCIAL
POLIETILENOS Y PRODUCTOS DE QUERETARO
PÚBLICO EN GENERAL
DISTRIBUIDORA LIVERPOOL
TRATAMIENTOS TERMICOS DE QUERETARO
PÚBLICO EN GENERAL
CAPTIVE SPORT
HEVACSA TERMOENCOGIBLES
ELECTRO FERRETERA REAL
SCIMPLA
ANA KARLA ROSALES VAZQUEZ
LBQ FOUNDRY
MANUFACTURERA SLY
PÚBLICO EN GENERAL
J H MILLS
PÚBLICO EN GENERAL
BURBUPAC DE QUERETARO
AT Y V DESARROLLOS Y MANUFACTURAS
PÚBLICO EN GENERAL
OLMO RACKS & DUNNAGE
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
PÚBLICO EN GENERAL
FISHERS QUERETARO

In [9]:
#Convertir cada nombre a minúsculas
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.lower())

donga hwasung mexico
donga hwasung mexico
proveedora de seguridad industrial del golfo
industrias lancermex
helvex
autoliv steering wheels mexico
autoliv steering wheels mexico
bussmann
clavos nacionales c.n
clavos nacionales c.n
richalum
transportadores y fabricaciones industriales
industrias lancermex
proveedora de seguridad industrial del golfo
autoliv steering wheels mexico
pquisem
siegfried rhein
siegfried rhein
molinera de mexico
q seals de mexico
q seals de mexico
siegfried rhein
proveedora de seguridad industrial del golfo
deacero
te.mex automotive
diecasting celaya
clavos nacionales c.n
cereales y pastas
plenco de mexico
proveedora de seguridad industrial del golfo
deacero
glasser
nestle mexico
airbus helicopters mexico queretaro
airbus helicopters mexico queretaro
sika mexicana
covemex
hot melt sistemas y servicios sanchez
edgar garcia hernandez
bussmann
sika mexicana
dwk life sciences
siegfried rhein
donga hwasung mexico
bachoco
siegfried rhein
preformados de mexico
cereales y pastas
empacadora celaya
fideicomiso f/1596
dwk life sciences
donga hwasung mexico
deacero
proveedora de seguridad industrial del golfo
proveedora de seguridad industrial del golfo
transportadores y fabricaciones industriales
beta procesos
deacero
bedacom
nihon plast mexicana
glasser
cereales y pastas
frescos don gu
deacero
kern liebers mexico
pquisem
edgar garcia hernandez
kern liebers mexico
deacero
controladora mabe
itw poly mex
ana barbara cruz palacios
armando vidaurreta peña
cereales y pastas
distribuciones y representaciones calora
oerlikon balzers coating mexico
apex tool group manufacturing mexico
siegfried rhein
transportadores y fabricaciones industriales
hobby electronica
david licea panduro
cereales y pastas
industrias toljy
sanko gosei mexico
vinilos
construcciones electromecanicas y servicios industriales
edgar garcia hernandez
kern liebers mexico
rl electrico
beta procesos
itw poly mex
performance coating
advanex de mexico
j. francisco ferruzca hernandez
deacero
mantenimiento de aire refrigeracion y calefaccion del centro
productos pennsylvania
siegfried rhein
mexicana de ingenieria y maquinaria
apex tool group manufacturing mexico
productos pennsylvania
público en general
raul servin aguillon
blanca rocio garcia morales
vinilos
alimentos gourmet del bajio
deacero
jorge herbert perez
captive sport
cereales y pastas
elastomeros de queretaro
abastecedora gourmet
lbq foundry
frescopack
mari carmen alonzo mora
hospital san jose de celaya
suajados especiales y maquila de empaque industrial
carlos alberto hernandez miranda
dex star
vinilos
emz hanauer de mexico
osania cleaning & sanitizing
kern liebers mexico
mecaprim servicios industriales
jakba-see
multi equipos automotrices vizu
grupo roce industrial y comercial
jose alejandro diaz nieto
grupo roce industrial y comercial
público en general
público en general
público en general
termoformados
marathon systems control
francisco javier medina sanchez
gabriela garcia sanchez
mecaprim servicios industriales
jose alejandro diaz nieto
jv agro
uch comercial
polietilenos y productos de queretaro
público en general
distribuidora liverpool
tratamientos termicos de queretaro
público en general
captive sport
hevacsa termoencogibles
electro ferretera real
scimpla
ana karla rosales vazquez
lbq foundry
manufacturera sly
público en general
j h mills
público en general
burbupac de queretaro
at y v desarrollos y manufacturas
público en general
olmo racks & dunnage
centro de investigacion y de estudios avanzados del instituto politecnico nacional
público en general
público en general
público en general
fishers queretaro

In [10]:
#Convertir la primera letra del registro en mayúscula
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.capitalize())

Donga hwasung mexico
Donga hwasung mexico
Proveedora de seguridad industrial del golfo
Industrias lancermex
Helvex
Autoliv steering wheels mexico
Autoliv steering wheels mexico
Bussmann
Clavos nacionales c.n
Clavos nacionales c.n
Richalum
Transportadores y fabricaciones industriales
Industrias lancermex
Proveedora de seguridad industrial del golfo
Autoliv steering wheels mexico
Pquisem
Siegfried rhein
Siegfried rhein
Molinera de mexico
Q seals de mexico
Q seals de mexico
Siegfried rhein
Proveedora de seguridad industrial del golfo
Deacero
Te.mex automotive
Diecasting celaya
Clavos nacionales c.n
Cereales y pastas
Plenco de mexico
Proveedora de seguridad industrial del golfo
Deacero
Glasser
Nestle mexico
Airbus helicopters mexico queretaro
Airbus helicopters mexico queretaro
Sika mexicana
Covemex
Hot melt sistemas y servicios sanchez
Edgar garcia hernandez
Bussmann
Sika mexicana
Dwk life sciences
Siegfried rhein
Donga hwasung mexico
Bachoco
Siegfried rhein
Preformados de mexico
Cereales y pastas
Empacadora celaya
Fideicomiso f/1596
Dwk life sciences
Donga hwasung mexico
Deacero
Proveedora de seguridad industrial del golfo
Proveedora de seguridad industrial del golfo
Transportadores y fabricaciones industriales
Beta procesos
Deacero
Bedacom
Nihon plast mexicana
Glasser
Cereales y pastas
Frescos don gu
Deacero
Kern liebers mexico
Pquisem
Edgar garcia hernandez
Kern liebers mexico
Deacero
Controladora mabe
Itw poly mex
Ana barbara cruz palacios
Armando vidaurreta peña
Cereales y pastas
Distribuciones y representaciones calora
Oerlikon balzers coating mexico
Apex tool group manufacturing mexico
Siegfried rhein
Transportadores y fabricaciones industriales
Hobby electronica
David licea panduro
Cereales y pastas
Industrias toljy
Sanko gosei mexico
Vinilos
Construcciones electromecanicas y servicios industriales
Edgar garcia hernandez
Kern liebers mexico
Rl electrico
Beta procesos
Itw poly mex
Performance coating
Advanex de mexico
J. francisco ferruzca hernandez
Deacero
Mantenimiento de aire refrigeracion y calefaccion del centro
Productos pennsylvania
Siegfried rhein
Mexicana de ingenieria y maquinaria
Apex tool group manufacturing mexico
Productos pennsylvania
Público en general
Raul servin aguillon
Blanca rocio garcia morales
Vinilos
Alimentos gourmet del bajio
Deacero
Jorge herbert perez
Captive sport
Cereales y pastas
Elastomeros de queretaro
Abastecedora gourmet
Lbq foundry
Frescopack
Mari carmen alonzo mora
Hospital san jose de celaya
Suajados especiales y maquila de empaque industrial
Carlos alberto hernandez miranda
Dex star
Vinilos
Emz hanauer de mexico
Osania cleaning & sanitizing
Kern liebers mexico
Mecaprim servicios industriales
Jakba-see
Multi equipos automotrices vizu
Grupo roce industrial y comercial
Jose alejandro diaz nieto
Grupo roce industrial y comercial
Público en general
Público en general
Público en general
Termoformados
Marathon systems control
Francisco javier medina sanchez
Gabriela garcia sanchez
Mecaprim servicios industriales
Jose alejandro diaz nieto
Jv agro
Uch comercial
Polietilenos y productos de queretaro
Público en general
Distribuidora liverpool
Tratamientos termicos de queretaro
Público en general
Captive sport
Hevacsa termoencogibles
Electro ferretera real
Scimpla
Ana karla rosales vazquez
Lbq foundry
Manufacturera sly
Público en general
J h mills
Público en general
Burbupac de queretaro
At y v desarrollos y manufacturas
Público en general
Olmo racks & dunnage
Centro de investigacion y de estudios avanzados del instituto politecnico nacional
Público en general
Público en general
Público en general
Fishers queretaro

In [11]:
#Convertir la primera letra de cada palabra en mayúscula
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre.title())

Donga Hwasung Mexico
Donga Hwasung Mexico
Proveedora De Seguridad Industrial Del Golfo
Industrias Lancermex
Helvex
Autoliv Steering Wheels Mexico
Autoliv Steering Wheels Mexico
Bussmann
Clavos Nacionales C.N
Clavos Nacionales C.N
Richalum
Transportadores Y Fabricaciones Industriales
Industrias Lancermex
Proveedora De Seguridad Industrial Del Golfo
Autoliv Steering Wheels Mexico
Pquisem
Siegfried Rhein
Siegfried Rhein
Molinera De Mexico
Q Seals De Mexico
Q Seals De Mexico
Siegfried Rhein
Proveedora De Seguridad Industrial Del Golfo
Deacero
Te.Mex Automotive
Diecasting Celaya
Clavos Nacionales C.N
Cereales Y Pastas
Plenco De Mexico
Proveedora De Seguridad Industrial Del Golfo
Deacero
Glasser
Nestle Mexico
Airbus Helicopters Mexico Queretaro
Airbus Helicopters Mexico Queretaro
Sika Mexicana
Covemex
Hot Melt Sistemas Y Servicios Sanchez
Edgar Garcia Hernandez
Bussmann
Sika Mexicana
Dwk Life Sciences
Siegfried Rhein
Donga Hwasung Mexico
Bachoco
Siegfried Rhein
Preformados De Mexico
Cereales Y Pastas
Empacadora Celaya
Fideicomiso F/1596
Dwk Life Sciences
Donga Hwasung Mexico
Deacero
Proveedora De Seguridad Industrial Del Golfo
Proveedora De Seguridad Industrial Del Golfo
Transportadores Y Fabricaciones Industriales
Beta Procesos
Deacero
Bedacom
Nihon Plast Mexicana
Glasser
Cereales Y Pastas
Frescos Don Gu
Deacero
Kern Liebers Mexico
Pquisem
Edgar Garcia Hernandez
Kern Liebers Mexico
Deacero
Controladora Mabe
Itw Poly Mex
Ana Barbara Cruz Palacios
Armando Vidaurreta Peña
Cereales Y Pastas
Distribuciones Y Representaciones Calora
Oerlikon Balzers Coating Mexico
Apex Tool Group Manufacturing Mexico
Siegfried Rhein
Transportadores Y Fabricaciones Industriales
Hobby Electronica
David Licea Panduro
Cereales Y Pastas
Industrias Toljy
Sanko Gosei Mexico
Vinilos
Construcciones Electromecanicas Y Servicios Industriales
Edgar Garcia Hernandez
Kern Liebers Mexico
Rl Electrico
Beta Procesos
Itw Poly Mex
Performance Coating
Advanex De Mexico
J. Francisco Ferruzca Hernandez
Deacero
Mantenimiento De Aire Refrigeracion Y Calefaccion Del Centro
Productos Pennsylvania
Siegfried Rhein
Mexicana De Ingenieria Y Maquinaria
Apex Tool Group Manufacturing Mexico
Productos Pennsylvania
Público En General
Raul Servin Aguillon
Blanca Rocio Garcia Morales
Vinilos
Alimentos Gourmet Del Bajio
Deacero
Jorge Herbert Perez
Captive Sport
Cereales Y Pastas
Elastomeros De Queretaro
Abastecedora Gourmet
Lbq Foundry
Frescopack
Mari Carmen Alonzo Mora
Hospital San Jose De Celaya
Suajados Especiales Y Maquila De Empaque Industrial
Carlos Alberto Hernandez Miranda
Dex Star
Vinilos
Emz Hanauer De Mexico
Osania Cleaning & Sanitizing
Kern Liebers Mexico
Mecaprim Servicios Industriales
Jakba-See
Multi Equipos Automotrices Vizu
Grupo Roce Industrial Y Comercial
Jose Alejandro Diaz Nieto
Grupo Roce Industrial Y Comercial
Público En General
Público En General
Público En General
Termoformados
Marathon Systems Control
Francisco Javier Medina Sanchez
Gabriela Garcia Sanchez
Mecaprim Servicios Industriales
Jose Alejandro Diaz Nieto
Jv Agro
Uch Comercial
Polietilenos Y Productos De Queretaro
Público En General
Distribuidora Liverpool
Tratamientos Termicos De Queretaro
Público En General
Captive Sport
Hevacsa Termoencogibles
Electro Ferretera Real
Scimpla
Ana Karla Rosales Vazquez
Lbq Foundry
Manufacturera Sly
Público En General
J H Mills
Público En General
Burbupac De Queretaro
At Y V Desarrollos Y Manufacturas
Público En General
Olmo Racks & Dunnage
Centro De Investigacion Y De Estudios Avanzados Del Instituto Politecnico Nacional
Público En General
Público En General
Público En General
Fishers Queretaro

In [12]:
#Contar cuántas letras tiene cada nombre
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(nombre, "tiene", len(nombre), "letras")

DONGA HWASUNG MEXICO tiene 20 letras
DONGA HWASUNG MEXICO tiene 20 letras
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO tiene 44 letras
INDUSTRIAS LANCERMEX tiene 20 letras
HELVEX tiene 6 letras
AUTOLIV STEERING WHEELS MEXICO tiene 30 letras
AUTOLIV STEERING WHEELS MEXICO tiene 30 letras
BUSSMANN tiene 8 letras
CLAVOS NACIONALES C.N tiene 21 letras
CLAVOS NACIONALES C.N tiene 21 letras
RICHALUM tiene 8 letras
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES tiene 44 letras
INDUSTRIAS LANCERMEX tiene 20 letras
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO tiene 44 letras
AUTOLIV STEERING WHEELS MEXICO tiene 30 letras
PQUISEM tiene 7 letras
SIEGFRIED RHEIN tiene 15 letras
SIEGFRIED RHEIN tiene 15 letras
MOLINERA DE MEXICO tiene 18 letras
Q SEALS DE MEXICO tiene 17 letras
Q SEALS DE MEXICO tiene 17 letras
SIEGFRIED RHEIN tiene 15 letras
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO tiene 44 letras
DEACERO tiene 7 letras
TE.MEX AUTOMOTIVE tiene 17 letras
DIECASTING CELAYA tiene 17 letras
CLAVOS NACIONALES C.N tiene 21 letras
CEREALES Y PASTAS tiene 17 letras
PLENCO DE MEXICO tiene 16 letras
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO tiene 44 letras
DEACERO tiene 7 letras
GLASSER tiene 7 letras
NESTLE MEXICO tiene 13 letras
AIRBUS HELICOPTERS MEXICO QUERETARO tiene 35 letras
AIRBUS HELICOPTERS MEXICO QUERETARO tiene 35 letras
SIKA MEXICANA tiene 13 letras
COVEMEX tiene 7 letras
HOT MELT SISTEMAS Y SERVICIOS SANCHEZ tiene 37 letras
EDGAR GARCIA HERNANDEZ tiene 22 letras
BUSSMANN tiene 8 letras
SIKA MEXICANA tiene 13 letras
DWK LIFE SCIENCES tiene 17 letras
SIEGFRIED RHEIN tiene 15 letras
DONGA HWASUNG MEXICO tiene 20 letras
BACHOCO tiene 7 letras
SIEGFRIED RHEIN tiene 15 letras
PREFORMADOS DE MEXICO tiene 21 letras
CEREALES Y PASTAS tiene 17 letras
EMPACADORA CELAYA tiene 17 letras
FIDEICOMISO F/1596 tiene 18 letras
DWK LIFE SCIENCES tiene 17 letras
DONGA HWASUNG MEXICO tiene 20 letras
DEACERO tiene 7 letras
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO tiene 44 letras
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO tiene 44 letras
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES tiene 44 letras
BETA PROCESOS tiene 13 letras
DEACERO tiene 7 letras
BEDACOM tiene 7 letras
NIHON PLAST MEXICANA tiene 20 letras
GLASSER tiene 7 letras
CEREALES Y PASTAS tiene 17 letras
FRESCOS DON GU tiene 14 letras
DEACERO tiene 7 letras
KERN LIEBERS MEXICO tiene 19 letras
PQUISEM tiene 7 letras
EDGAR GARCIA HERNANDEZ tiene 22 letras
KERN LIEBERS MEXICO tiene 19 letras
DEACERO tiene 7 letras
CONTROLADORA MABE tiene 17 letras
ITW POLY MEX tiene 12 letras
ANA BARBARA CRUZ PALACIOS tiene 25 letras
ARMANDO VIDAURRETA PEÑA tiene 23 letras
CEREALES Y PASTAS tiene 17 letras
DISTRIBUCIONES Y REPRESENTACIONES CALORA tiene 40 letras
OERLIKON BALZERS COATING MEXICO tiene 31 letras
APEX TOOL GROUP MANUFACTURING MEXICO tiene 36 letras
SIEGFRIED RHEIN tiene 15 letras
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES tiene 44 letras
HOBBY ELECTRONICA tiene 17 letras
DAVID LICEA PANDURO tiene 19 letras
CEREALES Y PASTAS tiene 17 letras
INDUSTRIAS TOLJY tiene 16 letras
SANKO GOSEI MEXICO tiene 18 letras
VINILOS tiene 7 letras
CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS INDUSTRIALES tiene 56 letras
EDGAR GARCIA HERNANDEZ tiene 22 letras
KERN LIEBERS MEXICO tiene 19 letras
RL ELECTRICO tiene 12 letras
BETA PROCESOS tiene 13 letras
ITW POLY MEX tiene 12 letras
PERFORMANCE COATING tiene 19 letras
ADVANEX DE MEXICO tiene 17 letras
J. FRANCISCO FERRUZCA HERNANDEZ tiene 31 letras
DEACERO tiene 7 letras
MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACCION DEL CENTRO tiene 60 letras
PRODUCTOS PENNSYLVANIA tiene 22 letras
SIEGFRIED RHEIN tiene 15 letras
MEXICANA DE INGENIERIA Y MAQUINARIA tiene 35 letras
APEX TOOL GROUP MANUFACTURING MEXICO tiene 36 letras
PRODUCTOS PENNSYLVANIA tiene 22 letras
PÚBLICO EN GENERAL tiene 18 letras
RAUL SERVIN AGUILLON tiene 20 letras
BLANCA ROCIO GARCIA MORALES tiene 27 letras
VINILOS tiene 7 letras
ALIMENTOS GOURMET DEL BAJIO tiene 27 letras
DEACERO tiene 7 letras
JORGE HERBERT PEREZ tiene 19 letras
CAPTIVE SPORT tiene 13 letras
CEREALES Y PASTAS tiene 17 letras
ELASTOMEROS DE QUERETARO tiene 24 letras
ABASTECEDORA GOURMET tiene 20 letras
LBQ FOUNDRY tiene 11 letras
FRESCOPACK tiene 10 letras
MARI CARMEN ALONZO MORA tiene 23 letras
HOSPITAL SAN JOSE DE CELAYA tiene 27 letras
SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUSTRIAL tiene 51 letras
CARLOS ALBERTO HERNANDEZ MIRANDA tiene 32 letras
DEX STAR tiene 8 letras
VINILOS tiene 7 letras
EMZ HANAUER DE MEXICO tiene 21 letras
OSANIA CLEANING & SANITIZING tiene 28 letras
KERN LIEBERS MEXICO tiene 19 letras
MECAPRIM SERVICIOS INDUSTRIALES tiene 31 letras
JAKBA-SEE tiene 9 letras
MULTI EQUIPOS AUTOMOTRICES VIZU tiene 31 letras
GRUPO ROCE INDUSTRIAL Y COMERCIAL tiene 33 letras
JOSE ALEJANDRO DIAZ NIETO tiene 25 letras
GRUPO ROCE INDUSTRIAL Y COMERCIAL tiene 33 letras
PÚBLICO EN GENERAL tiene 18 letras
PÚBLICO EN GENERAL tiene 18 letras
PÚBLICO EN GENERAL tiene 18 letras
TERMOFORMADOS tiene 13 letras
MARATHON SYSTEMS CONTROL tiene 24 letras
FRANCISCO JAVIER MEDINA SANCHEZ tiene 31 letras
GABRIELA GARCIA SANCHEZ tiene 23 letras
MECAPRIM SERVICIOS INDUSTRIALES tiene 31 letras
JOSE ALEJANDRO DIAZ NIETO tiene 25 letras
JV AGRO tiene 7 letras
UCH COMERCIAL tiene 13 letras
POLIETILENOS Y PRODUCTOS DE QUERETARO tiene 37 letras
PÚBLICO EN GENERAL tiene 18 letras
DISTRIBUIDORA LIVERPOOL tiene 23 letras
TRATAMIENTOS TERMICOS DE QUERETARO tiene 34 letras
PÚBLICO EN GENERAL tiene 18 letras
CAPTIVE SPORT tiene 13 letras
HEVACSA TERMOENCOGIBLES tiene 23 letras
ELECTRO FERRETERA REAL tiene 22 letras
SCIMPLA tiene 7 letras
ANA KARLA ROSALES VAZQUEZ tiene 25 letras
LBQ FOUNDRY tiene 11 letras
MANUFACTURERA SLY tiene 17 letras
PÚBLICO EN GENERAL tiene 18 letras
J H MILLS tiene 9 letras
PÚBLICO EN GENERAL tiene 18 letras
BURBUPAC DE QUERETARO tiene 21 letras
AT Y V DESARROLLOS Y MANUFACTURAS tiene 33 letras
PÚBLICO EN GENERAL tiene 18 letras
OLMO RACKS & DUNNAGE tiene 20 letras
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL tiene 82 letras
PÚBLICO EN GENERAL tiene 18 letras
PÚBLICO EN GENERAL tiene 18 letras
PÚBLICO EN GENERAL tiene 18 letras
FISHERS QUERETARO tiene 17 letras

In [13]:
#Mostrar solamente los nombres que tienen menos de 15 letras
for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    
    if len(nombre) < 15:
        print(nombre)

HELVEX
BUSSMANN
RICHALUM
PQUISEM
DEACERO
DEACERO
GLASSER
NESTLE MEXICO
SIKA MEXICANA
COVEMEX
BUSSMANN
SIKA MEXICANA
BACHOCO
DEACERO
BETA PROCESOS
DEACERO
BEDACOM
GLASSER
FRESCOS DON GU
DEACERO
PQUISEM
DEACERO
ITW POLY MEX
VINILOS
RL ELECTRICO
BETA PROCESOS
ITW POLY MEX
DEACERO
VINILOS
DEACERO
CAPTIVE SPORT
LBQ FOUNDRY
FRESCOPACK
DEX STAR
VINILOS
JAKBA-SEE
TERMOFORMADOS
JV AGRO
UCH COMERCIAL
CAPTIVE SPORT
SCIMPLA
LBQ FOUNDRY
J H MILLS

In [14]:
#Crear un saludo para cada nombre
def saludar(nombre):
    return "Hola " + nombre + ", bienvenid@!"

for nombre in np.nditer(nombres, flags=['refs_ok']):
    nombre = nombre.item()
    print(saludar(nombre))

Hola DONGA HWASUNG MEXICO, bienvenid@!
Hola DONGA HWASUNG MEXICO, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola INDUSTRIAS LANCERMEX, bienvenid@!
Hola HELVEX, bienvenid@!
Hola AUTOLIV STEERING WHEELS MEXICO, bienvenid@!
Hola AUTOLIV STEERING WHEELS MEXICO, bienvenid@!
Hola BUSSMANN, bienvenid@!
Hola CLAVOS NACIONALES C.N, bienvenid@!
Hola CLAVOS NACIONALES C.N, bienvenid@!
Hola RICHALUM, bienvenid@!
Hola TRANSPORTADORES Y FABRICACIONES INDUSTRIALES, bienvenid@!
Hola INDUSTRIAS LANCERMEX, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola AUTOLIV STEERING WHEELS MEXICO, bienvenid@!
Hola PQUISEM, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola MOLINERA DE MEXICO, bienvenid@!
Hola Q SEALS DE MEXICO, bienvenid@!
Hola Q SEALS DE MEXICO, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola DEACERO, bienvenid@!
Hola TE.MEX AUTOMOTIVE, bienvenid@!
Hola DIECASTING CELAYA, bienvenid@!
Hola CLAVOS NACIONALES C.N, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola PLENCO DE MEXICO, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola DEACERO, bienvenid@!
Hola GLASSER, bienvenid@!
Hola NESTLE MEXICO, bienvenid@!
Hola AIRBUS HELICOPTERS MEXICO QUERETARO, bienvenid@!
Hola AIRBUS HELICOPTERS MEXICO QUERETARO, bienvenid@!
Hola SIKA MEXICANA, bienvenid@!
Hola COVEMEX, bienvenid@!
Hola HOT MELT SISTEMAS Y SERVICIOS SANCHEZ, bienvenid@!
Hola EDGAR GARCIA HERNANDEZ, bienvenid@!
Hola BUSSMANN, bienvenid@!
Hola SIKA MEXICANA, bienvenid@!
Hola DWK LIFE SCIENCES, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola DONGA HWASUNG MEXICO, bienvenid@!
Hola BACHOCO, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola PREFORMADOS DE MEXICO, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola EMPACADORA CELAYA, bienvenid@!
Hola FIDEICOMISO F/1596, bienvenid@!
Hola DWK LIFE SCIENCES, bienvenid@!
Hola DONGA HWASUNG MEXICO, bienvenid@!
Hola DEACERO, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO, bienvenid@!
Hola TRANSPORTADORES Y FABRICACIONES INDUSTRIALES, bienvenid@!
Hola BETA PROCESOS, bienvenid@!
Hola DEACERO, bienvenid@!
Hola BEDACOM, bienvenid@!
Hola NIHON PLAST MEXICANA, bienvenid@!
Hola GLASSER, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola FRESCOS DON GU, bienvenid@!
Hola DEACERO, bienvenid@!
Hola KERN LIEBERS MEXICO, bienvenid@!
Hola PQUISEM, bienvenid@!
Hola EDGAR GARCIA HERNANDEZ, bienvenid@!
Hola KERN LIEBERS MEXICO, bienvenid@!
Hola DEACERO, bienvenid@!
Hola CONTROLADORA MABE, bienvenid@!
Hola ITW POLY MEX, bienvenid@!
Hola ANA BARBARA CRUZ PALACIOS, bienvenid@!
Hola ARMANDO VIDAURRETA PEÑA, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola DISTRIBUCIONES Y REPRESENTACIONES CALORA, bienvenid@!
Hola OERLIKON BALZERS COATING MEXICO, bienvenid@!
Hola APEX TOOL GROUP MANUFACTURING MEXICO, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola TRANSPORTADORES Y FABRICACIONES INDUSTRIALES, bienvenid@!
Hola HOBBY ELECTRONICA, bienvenid@!
Hola DAVID LICEA PANDURO, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola INDUSTRIAS TOLJY, bienvenid@!
Hola SANKO GOSEI MEXICO, bienvenid@!
Hola VINILOS, bienvenid@!
Hola CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS INDUSTRIALES, bienvenid@!
Hola EDGAR GARCIA HERNANDEZ, bienvenid@!
Hola KERN LIEBERS MEXICO, bienvenid@!
Hola RL ELECTRICO, bienvenid@!
Hola BETA PROCESOS, bienvenid@!
Hola ITW POLY MEX, bienvenid@!
Hola PERFORMANCE COATING, bienvenid@!
Hola ADVANEX DE MEXICO, bienvenid@!
Hola J. FRANCISCO FERRUZCA HERNANDEZ, bienvenid@!
Hola DEACERO, bienvenid@!
Hola MANTENIMIENTO DE AIRE REFRIGERACION Y CALEFACCION DEL CENTRO, bienvenid@!
Hola PRODUCTOS PENNSYLVANIA, bienvenid@!
Hola SIEGFRIED RHEIN, bienvenid@!
Hola MEXICANA DE INGENIERIA Y MAQUINARIA, bienvenid@!
Hola APEX TOOL GROUP MANUFACTURING MEXICO, bienvenid@!
Hola PRODUCTOS PENNSYLVANIA, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola RAUL SERVIN AGUILLON, bienvenid@!
Hola BLANCA ROCIO GARCIA MORALES, bienvenid@!
Hola VINILOS, bienvenid@!
Hola ALIMENTOS GOURMET DEL BAJIO, bienvenid@!
Hola DEACERO, bienvenid@!
Hola JORGE HERBERT PEREZ, bienvenid@!
Hola CAPTIVE SPORT, bienvenid@!
Hola CEREALES Y PASTAS, bienvenid@!
Hola ELASTOMEROS DE QUERETARO, bienvenid@!
Hola ABASTECEDORA GOURMET, bienvenid@!
Hola LBQ FOUNDRY, bienvenid@!
Hola FRESCOPACK, bienvenid@!
Hola MARI CARMEN ALONZO MORA, bienvenid@!
Hola HOSPITAL SAN JOSE DE CELAYA, bienvenid@!
Hola SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUSTRIAL, bienvenid@!
Hola CARLOS ALBERTO HERNANDEZ MIRANDA, bienvenid@!
Hola DEX STAR, bienvenid@!
Hola VINILOS, bienvenid@!
Hola EMZ HANAUER DE MEXICO, bienvenid@!
Hola OSANIA CLEANING & SANITIZING, bienvenid@!
Hola KERN LIEBERS MEXICO, bienvenid@!
Hola MECAPRIM SERVICIOS INDUSTRIALES, bienvenid@!
Hola JAKBA-SEE, bienvenid@!
Hola MULTI EQUIPOS AUTOMOTRICES VIZU, bienvenid@!
Hola GRUPO ROCE INDUSTRIAL Y COMERCIAL, bienvenid@!
Hola JOSE ALEJANDRO DIAZ NIETO, bienvenid@!
Hola GRUPO ROCE INDUSTRIAL Y COMERCIAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola TERMOFORMADOS, bienvenid@!
Hola MARATHON SYSTEMS CONTROL, bienvenid@!
Hola FRANCISCO JAVIER MEDINA SANCHEZ, bienvenid@!
Hola GABRIELA GARCIA SANCHEZ, bienvenid@!
Hola MECAPRIM SERVICIOS INDUSTRIALES, bienvenid@!
Hola JOSE ALEJANDRO DIAZ NIETO, bienvenid@!
Hola JV AGRO, bienvenid@!
Hola UCH COMERCIAL, bienvenid@!
Hola POLIETILENOS Y PRODUCTOS DE QUERETARO, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola DISTRIBUIDORA LIVERPOOL, bienvenid@!
Hola TRATAMIENTOS TERMICOS DE QUERETARO, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola CAPTIVE SPORT, bienvenid@!
Hola HEVACSA TERMOENCOGIBLES, bienvenid@!
Hola ELECTRO FERRETERA REAL, bienvenid@!
Hola SCIMPLA, bienvenid@!
Hola ANA KARLA ROSALES VAZQUEZ, bienvenid@!
Hola LBQ FOUNDRY, bienvenid@!
Hola MANUFACTURERA SLY, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola J H MILLS, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola BURBUPAC DE QUERETARO, bienvenid@!
Hola AT Y V DESARROLLOS Y MANUFACTURAS, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola OLMO RACKS & DUNNAGE, bienvenid@!
Hola CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola PÚBLICO EN GENERAL, bienvenid@!
Hola FISHERS QUERETARO, bienvenid@!

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [16]:
#Filtro por objeto
filtro1=df[df["NOMBRE"] == "INDUSTRIAS LANCERMEX"]
filtro1

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
12,3930,INDUSTRIAS LANCERMEX,F40114,2023-02-09,2023-03-11,35143.82

In [15]:
#Filtro por filas
#filtro2= df.iloc[3:11,: ]           #Filas consecutivas
#filtro2=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas
filtro2= df.iloc[ [0] + list(range(10, 14)) + [50] , : ]  #Filas combinadas
filtro2

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
10,3937,RICHALUM,F40361,2023-03-14,2023-03-14,42880.05
11,2046,TRANSPORTADORES Y FABRICACIONES INDUSTRIALES,F40118,2023-02-10,2023-03-12,37588.59
12,3930,INDUSTRIAS LANCERMEX,F40114,2023-02-09,2023-03-11,35143.82
13,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40171,2023-02-17,2023-03-19,34493.76
50,6396,DWK LIFE SCIENCES,F40209,2023-02-22,2023-03-24,9472.53

In [17]:
#Filtro por columnas
#filtro3=df.iloc[ : , 0:3]       #Columnas consecutivas
#filtro3=df.iloc[ : , [1,4,6]]  #Columnas no consecutivas
filtro3= df.iloc[ :, [0] + list(range(1, 4)) + [5] ]  #Filas combinadas
filtro3

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,52715.74
4,4712,HELVEX,F40173,2023-02-17,50639.80
...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,19.94

In [18]:
#GOOGLE COLAB
#Filtro de filas vs columnas
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()

ModuleNotFoundError: No module named 'google'

In [19]:
df1= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx', index_col=1)
df1

,No. CLIENTE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
NOMBRE,,,,,
DONGA HWASUNG MEXICO,6401,F40238,2023-02-24,2023-03-26,97485.94
DONGA HWASUNG MEXICO,6401,F40353,2023-03-14,2023-04-13,97485.94
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,4598,F40352,2023-03-14,2023-04-13,64916.21
INDUSTRIAS LANCERMEX,3930,F40217,2023-02-23,2023-03-25,52715.74
HELVEX,4712,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL,856,F40055,2023-01-31,2023-01-31,56.00
PÚBLICO EN GENERAL,5926,NV00777,2023-03-07,2023-03-07,45.00
PÚBLICO EN GENERAL,5926,NV00778,2023-03-09,2023-03-09,40.00
PÚBLICO EN GENERAL,5926,NV00779,2023-03-09,2023-03-09,24.01
FISHERS QUERETARO,8429,F38248,2022-05-27,2022-05-27,19.94

In [20]:
#Paso 2: Aplicamos Filtro de filas vs columnas
filtro4=df1.loc[["HELVEX","DONGA HWASUNG MEXICO"], ["MONTO ADEUDADO"]]
filtro4

                      MONTO ADEUDADO
NOMBRE
HELVEX                      50639.80
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        10759.00
DONGA HWASUNG MEXICO         9396.00

In [21]:
#Filtro por cabecera
filtro5=df.head()
filtro5

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80

In [22]:
#Filtro por cabecera
filtro6=df.tail()
filtro6

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [26]:
#Filtro por comparacion
filtro6=df[df["MONTO ADEUDADO"] < 1000]
filtro6

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
131,5926,PÚBLICO EN GENERAL,NV00356,2021-08-16,2021-08-16,815.00
132,1284,TERMOFORMADOS,F40349,2023-03-14,2023-04-13,799.24
133,2549,MARATHON SYSTEMS CONTROL,F39912,2023-01-12,2023-02-11,765.60
134,8434,FRANCISCO JAVIER MEDINA SANCHEZ,F39426,2022-10-27,2022-10-27,763.04
135,8872,GABRIELA GARCIA SANCHEZ,F40360,2023-03-14,2023-03-14,754.00
136,5598,MECAPRIM SERVICIOS INDUSTRIALES,F40369,2023-03-15,2023-03-15,742.40
137,6746,JOSE ALEJANDRO DIAZ NIETO,F40336,2023-03-10,2023-03-10,730.01
138,8545,JV AGRO,F40373,2023-03-15,2023-03-15,704.41
139,8228,UCH COMERCIAL,F40365,2023-03-14,2023-03-14,702.96
140,O,POLIETILENOS Y PRODUCTOS DE QUERETARO,F40374,2023-03-16,2023-03-16,658.60
141,5926,PÚBLICO EN GENERAL,NV00351,2021-08-06,2021-08-06,591.60
142,8564,DISTRIBUIDORA LIVERPOOL,F40348,2023-03-13,2023-03-13,568.40
143,357,TRATAMIENTOS TERMICOS DE QUERETARO,F39931,2023-01-17,2023-02-01,555.19
144,5926,PÚBLICO EN GENERAL,F36620,2021-11-09,2021-11-09,500.00
145,6885,CAPTIVE SPORT,F36062,2021-09-06,2021-09-06,500.00
146,7059,HEVACSA TERMOENCOGIBLES,F40311,2023-03-07,2023-03-07,487.20
147,8697,ELECTRO FERRETERA REAL,F40314,2023-03-08,2023-03-08,487.20
148,8243,SCIMPLA,F38125,2022-05-10,2022-05-10,420.00
149,8826,ANA KARLA ROSALES VAZQUEZ,F40097,2023-02-07,2023-02-07,406.00
150,161,LBQ FOUNDRY,F40161,2023-02-16,2023-03-18,366.04
151,8863,MANUFACTURERA SLY,F40334,2023-03-10,2023-03-10,313.50
152,5926,PÚBLICO EN GENERAL,NV00368,2021-08-26,2021-08-26,300.00
153,3011,J H MILLS,F40310,2023-03-07,2023-03-07,262.74
154,5926,PÚBLICO EN GENERAL,F35996,2021-08-31,2021-08-31,200.00
155,5936,BURBUPAC DE QUERETARO,F40318,2023-03-08,2023-04-07,191.04
156,6048,AT Y V DESARROLLOS Y MANUFACTURAS,F40370,2023-03-15,2023-03-15,139.20
157,5926,PÚBLICO EN GENERAL,NV00780,2023-03-13,2023-03-13,130.00
158,8698,OLMO RACKS & DUNNAGE,F38473,2022-06-28,2022-06-28,87.35
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

**FILTROS BASICOS CON CONETORES LOGICOS**

In [27]:
#Filtro Y
filtro7=df[(df["MONTO ADEUDADO"] < 6000) & (df["FECHA_FACTURA"] == "2023-03-14")]
filtro7

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
85,409,CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS IN...,F40359,2023-03-14,2023-03-14,4292.00
96,3926,PRODUCTOS PENNSYLVANIA,F40358,2023-03-14,2023-04-13,3368.64
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16
101,5926,PÚBLICO EN GENERAL,F40362,2023-03-14,2023-03-14,2694.95
113,2216,FRESCOPACK,F40355,2023-03-14,2023-03-14,1682.00
132,1284,TERMOFORMADOS,F40349,2023-03-14,2023-04-13,799.24
135,8872,GABRIELA GARCIA SANCHEZ,F40360,2023-03-14,2023-03-14,754.00
139,8228,UCH COMERCIAL,F40365,2023-03-14,2023-03-14,702.96

In [28]:
#Filtro o
filtro8=df[(df["MONTO ADEUDADO"] < 6000) | (df["FECHA_FACTURA"] == "2023-03-14")]
filtro8

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34
10,3937,RICHALUM,F40361,2023-03-14,2023-03-14,42880.05
36,417,COVEMEX,F40354,2023-03-14,2023-03-29,15843.28
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [32]:
#Filtro not
filtro9=df[~(df["MONTO ADEUDADO"] >= 6000)]
filtro9

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
70,1852,ITW POLY MEX,F40201,2023-02-22,2023-03-24,5967.85
71,8316,ANA BARBARA CRUZ PALACIOS,F40379,2023-03-16,2023-03-31,5827.84
72,8787,ARMANDO VIDAURRETA PEÑA,F39769,2022-12-14,2022-12-14,5800.00
73,2768,CEREALES Y PASTAS,F40215,2023-02-22,2023-03-24,5660.80
74,1831,DISTRIBUCIONES Y REPRESENTACIONES CALORA,F40316,2023-03-08,2023-04-22,5502.81
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [33]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("Entregable1.csv")

In [35]:
df=pd.read_csv("Datos_Facturación.csv")
df

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10890,10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaN,3272.00,0.0,0.0
10891,10891,F40307,6218.0,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,504.15,0.0,0.0
10892,10892,NaN,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,275.68,0.0,0.0
10893,10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaN,129.30,0.0,0.0
10894,10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaN,517.20,0.0,0.0

In [46]:
Inciso_1=df[(df["CVE_CLPV"] >= 1000) & (df["CVE_CLPV"] <=2000)]
Inciso_1

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.50,0.00,0.0
22,22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.50,0.00,0.0
65,65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaN,4135.00,0.00,0.0
71,71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.50,146.48,0.0
72,72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaN,976.50,146.48,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10821,10821,F40237,1757.0,E,2.0,2023-02-24 15:18:17.570,2023-02-24,2023-02-13 00:00:00,2023-02-24,NaN,10088.40,0.00,0.0
10839,10839,F40255,1583.0,E,2.0,2023-02-28 09:15:45.753,2023-02-28,2023-02-28 00:00:00,2023-03-30,NaN,3467.35,0.00,0.0
10845,10845,F40261,1786.0,E,2.0,2023-02-28 11:15:32.527,2023-02-28,2023-03-03 00:00:00,2023-02-28,NaN,4663.80,0.00,0.0
10871,10871,F40287,1453.0,E,1.0,2023-03-01 12:58:23.397,2023-03-01,2023-02-27 00:00:00,2023-03-31,NaN,9000.00,0.00,0.0
10876,10876,F40292,1082.0,E,6.0,2023-03-02 11:00:54.770,2023-03-02,2023-03-01 00:00:00,2023-03-02,NaN,3262.00,0.00,0.0

In [40]:
Inciso_1.to_csv("CVE_CLPV(valores_1000_a_2000).csv")

In [67]:
Inciso2 = df[(df["CVE_VEND"]!=5) & (df["CVE_VEND"]!=4)]
Inciso2

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10890,10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01,2023-03-06,NaN,3272.00,0.0,0.0
10891,10891,F40307,6218.0,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06,2023-03-06,NaN,504.15,0.0,0.0
10892,10892,NaN,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06,2023-03-06,NaN,275.68,0.0,0.0
10893,10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07,2023-03-07,NaN,129.30,0.0,0.0
10894,10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01,2023-03-07,NaN,517.20,0.0,0.0

In [71]:
Inciso2.to_csv("Inciso2.csv")

In [62]:
df["FECHA_ENT"] = pd.to_datetime(df["FECHA_ENT"], dayfirst=True)
inciso3 = df[df["FECHA_ENT"] == "2022-02-28"]
inciso3

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
8077,8077,F37493,4598.0,E,1.0,2022-02-28 10:56:02.460,2022-02-28,2022-02-28,2022-03-30,NaN,44259.0000,0.0,0.0
8078,8078,F37494,1943.0,C,2.0,2022-02-28 11:34:00.367,2022-02-28,2022-02-28,2022-02-28,2022-02-28,89.6800,0.0,0.0
8081,8081,F37497,1943.0,C,2.0,2022-02-28 12:05:42.377,2022-02-28,2022-02-28,2022-02-28,2022-02-28,89.6800,0.0,0.0
8083,8083,F37499,8573.0,E,2.0,2022-02-28 12:25:29.833,2022-02-28,2022-02-28,2022-02-28,NaN,997.5400,0.0,0.0
8084,8084,F37500,8249.0,E,2.0,2022-02-28 12:32:46.687,2022-02-28,2022-02-28,2022-02-28,NaN,2508.7000,0.0,0.0
8090,8090,F37506,1757.0,E,2.0,2022-02-28 13:23:45.440,2022-02-28,2022-02-28,2022-02-28,NaN,2586.2100,0.0,0.0
8091,8091,F37507,3108.0,E,2.0,2022-02-28 13:52:43.383,2022-02-28,2022-02-28,2022-02-28,NaN,675.4000,0.0,0.0
8092,8092,F37508,6232.0,E,2.0,2022-02-28 14:46:56.940,2022-02-28,2022-02-28,2022-02-28,NaN,941.3965,0.0,0.0
8095,8095,F37511,8593.0,E,2.0,2022-02-28 15:20:58.040,2022-02-28,2022-02-28,2022-02-28,NaN,218.9700,0.0,0.0
8096,8096,F37512,4766.0,E,2.0,2022-02-28 15:54:16.277,2022-02-28,2022-02-28,2022-02-28,NaN,9450.0000,0.0,0.0
8100,8100,F37516,6179.0,E,3.0,2022-02-28 16:33:54.413,2022-02-28,2022-02-28,2022-02-28,NaN,5951.7000,0.0,0.0
8103,8103,F37519,5150.0,E,3.0,2022-02-28 17:09:39.213,2022-02-28,2022-02-28,2022-02-28,NaN,2040.0000,0.0,0.0
8104,8104,F37520,4527.0,E,2.0,2022-02-28 17:14:57.487,2022-02-28,2022-02-28,2022-02-28,NaN,4315.0000,0.0,0.0
8107,8107,F37523,5926.0,E,2.0,2022-02-28 17:36:54.363,2022-02-28,2022-02-28,2022-02-28,NaN,451.6100,0.0,0.0
8133,8133,F37549,3016.0,E,1.0,2022-03-04 15:08:49.747,2022-03-04,2022-02-28,2022-03-04,NaN,1083.7200,0.0,0.0
8148,8148,F37564,4695.0,E,1.0,2022-03-08 09:15:20.507,2022-03-08,2022-02-28,2022-05-07,NaN,5515.0000,0.0,0.0
8204,8204,F37620,8316.0,E,3.0,2022-03-14 17:00:43.247,2022-03-14,2022-02-28,2022-03-14,NaN,24570.3000,0.0,0.0

In [72]:
inciso3.to_csv("Inciso3.csv")

In [63]:
inciso4 = df[(df["CAN_TOT"] < 5951.7) | (df["STATUS"] == "E")]
inciso4

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10890,10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01,2023-03-06,NaN,3272.00,0.0,0.0
10891,10891,F40307,6218.0,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06,2023-03-06,NaN,504.15,0.0,0.0
10892,10892,NaN,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06,2023-03-06,NaN,275.68,0.0,0.0
10893,10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07,2023-03-07,NaN,129.30,0.0,0.0
10894,10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01,2023-03-07,NaN,517.20,0.0,0.0

In [73]:
inciso4.to_csv("Inciso4.csv")

In [64]:
inciso5 = df[["CVE_DOC", "FECHA_ENT", "FECHA_VEN", "CAN_TOT"]]
inciso5

      CVE_DOC  FECHA_ENT   FECHA_VEN  CAN_TOT
0      F29414 2019-09-03  2019-09-18  3980.00
1      F29415 2019-09-03  2019-10-03  1550.00
2      F29416 2019-09-03  2019-10-03  1550.00
3      F29417 2019-09-03  2019-10-03  1550.00
4      F29418 2019-09-03  2019-09-03  2435.44
...       ...        ...         ...      ...
10890  F40306 2023-03-01  2023-03-06  3272.00
10891  F40307 2023-03-06  2023-03-06   504.15
10892     NaN 2023-03-06  2023-03-06   275.68
10893  F40309 2023-03-07  2023-03-07   129.30
10894  F40310 2023-03-01  2023-03-07   517.20

[10895 rows x 4 columns]

In [75]:
inciso5.to_csv("Inciso5.csv")

In [65]:
inciso6 = df.iloc[7001:7100]
inciso6

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
7001,7001,F36417,5271.0,E,3.0,2021-10-15 08:40:29.183,2021-10-15,2021-10-06,2021-11-14,NaN,8555.24,0.0,0.0
7002,7002,F36418,5746.0,E,2.0,2021-10-15 08:51:03.463,2021-10-15,2021-10-14,2021-10-15,NaN,620.77,0.0,0.0
7003,7003,F36419,2163.0,E,3.0,2021-10-15 08:56:23.280,2021-10-15,2021-10-15,2021-10-15,NaN,560.00,0.0,0.0
7004,7004,F36420,1429.0,E,1.0,2021-10-15 09:01:08.393,2021-10-15,2021-10-15,2021-12-14,NaN,23625.00,0.0,0.0
7005,7005,F36421,5039.0,E,1.0,2021-10-15 09:07:07.103,2021-10-15,2021-10-08,2022-01-13,NaN,3308.78,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7095,7095,F36511,4480.0,E,2.0,2021-10-27 13:07:43.223,2021-10-27,2021-10-27,2021-11-11,NaN,1137.50,0.0,0.0
7096,7096,F36512,8186.0,E,2.0,2021-10-27 13:22:23.980,2021-10-27,2021-10-27,2021-10-27,NaN,94.84,0.0,0.0
7097,7097,F36513,4403.0,E,2.0,2021-10-27 13:35:40.677,2021-10-27,2021-10-27,2021-10-27,NaN,847.00,0.0,0.0
7098,7098,F36514,5589.0,E,2.0,2021-10-27 14:02:54.630,2021-10-27,2021-10-27,2021-10-27,NaN,965.00,0.0,0.0
7099,7099,F36515,5589.0,E,2.0,2021-10-27 14:04:26.797,2021-10-27,2021-10-26,2021-10-27,NaN,2106.00,0.0,0.0

In [76]:
inciso6.to_csv("Inciso6.csv")

In [66]:
inciso7 = df[df["CVE_VEND"].isin([1, 2])]
inciso7 = inciso7.set_index("CVE_VEND")
inciso7 = inciso7[["FECHAELAB"]]
inciso7

                        FECHAELAB
CVE_VEND
1.0       2019-09-03 08:58:42.000
1.0       2019-09-03 09:55:14.000
1.0       2019-09-03 13:25:33.000
1.0       2019-09-03 13:33:23.000
2.0       2019-09-03 14:23:45.000
...                           ...
2.0       2023-03-06 16:09:39.013
2.0       2023-03-06 16:38:42.933
2.0       2023-03-06 17:02:33.390
2.0       2023-03-07 12:43:49.567
2.0       2023-03-07 12:45:58.407

[8665 rows x 1 columns]

In [77]:
inciso7.to_csv("Inciso7.csv")

In [31]:
#GOOGLE COLAB
#descardar archivo filtrado en csv
from google.colab import files


files.download("Entregable1.csv")

ModuleNotFoundError: No module named 'google'